### ISSUE TITLE
Clarification on License Needed

### ISSUE THREAD

**Issue by oberbeck** [un/webhook-proxy#8]
We are very intrigued by and interested in both using and potentially contributing to this project. However,
after reviewing the repository as well as Issue https://github.com/un/webhook-proxy/issues/1 it remains unclear which license applies to this repository.
Could you please clarify which license applies?

<img width="875" alt="Screenshot 2024-04-10 at 15 29 08" src="https://github.com/un/webhook-proxy/assets/20164654/1f70ae3e-b791-4171-b048-cbf3353c667a">
<img width="875" alt="Screenshot 2024-04-10 at 15 29 50" src="https://github.com/un/webhook-proxy/assets/20164654/4ebc8cd3-ba11-4b8b-b32d-127a0db291be">
<img width="875" alt="Screenshot 2024-04-10 at 15 29 58" src="https://github.com/un/webhook-proxy/assets/20164654/3aaeb8df-7153-4c32-94d0-011de362c59d">

**Comment by McPizza0** [comment]
License is MIT
